### ISSUE TITLE
Fails to load on Blender 4.0.1

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics_Blender_Exporter#4]
Not sure if this is something bad about my Blender install, but on 4.0.1-5, Arch Linux I get the following trying to enable the plugin:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/linus/.config/blender/4.0/scripts/addons/KHR_rigid_bodies/__init__.py", line 3, in <module>
    from .blender.com.gltf2_blender_rigid_bodies_ui import *
  File "/home/linus/.config/blender/4.0/scripts/addons/KHR_rigid_bodies/blender/com/gltf2_blender_rigid_bodies_ui.py", line 283, in <module>
    viewportRenderHelper = KHR_rigid_body_viewport_render()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linus/.config/blender/4.0/scripts/addons/KHR_rigid_bodies/blender/com/gltf2_blender_rigid_bodies_ui.py", line 82, in __init__
    self.shader = gpu.shader.from_builtin("3D_UNIFORM_COLOR")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'
```

**Comment by eoineoineoin** [comment]
Thanks. Looks like that enum was just renamed in Blender 4.

**Comment by Shinmera** [comment]
Thanks for the quick fix!
